{% set version = "1.0.0" %}

package:
  name: sarif-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sarif-tools/sarif-tools-{{ version }}.tar.gz
  sha256: e814d8249f6751f174d012c240b02601b877b78e5c4fe5dd00b30dc796f01ee4

build:
  entry_points:
    - sarif = sarif.cmdline.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - jinja2 >=3.1.2,<4.0.0
    - matplotlib-base >=3.5.1,<4.0.0
    - python >=3.8
    - python-docx >=0.8.11,<0.9.0

test:
  requires:
    - pip
    - m2-grep  # [win]
  imports:
    - sarif
  commands:
    - pip check
    - sarif --version
    - sarif --help
    - sarif --version | grep -iE "^sarif-tools version {{ version.replace(".", "\\.") }}$"

about:
  home: https://github.com/microsoft/sarif-tools
  summary: SARIF tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
